spring.application.name=ecommerce

# Tell Hibernate not to overwrite the data.sql inserts
spring.jpa.hibernate.ddl-auto=update

# Force Spring to run data.sql on startup
spring.sql.init.mode=never

# If you are using H2 (In-memory), this ensures the table exists before the SQL runs
spring.jpa.defer-datasource-initialization=true

# Database Connection Settings
spring.datasource.url=jdbc:mysql://localhost:3306/emply
spring.datasource.username=root
spring.datasource.password=hiya15
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate/JPA Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
