spring.application.name=ecommerce

# Use this EXACT format to allow Render to override local settings
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/emply}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:hiya15}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect